Repository mavidurak/orientation-api, pull requests merged in 2021-07, with the labels that each got.

#17 multiple router support added
  src/routes/index.js
Labels: enhancement

#19 added get operations of comments
  src/routes/comments/index.js
Labels: waiting for review

#21 Features for wanted list
  src/routes/wantedContents/index.js
Labels: enhancement, waiting for review

#20 Contents crud
  migrations/20210701182648-create-content.js
  src/models/contents.js
  src/models/images.js
  src/models/users.js
  src/routes/contents/index.js
  yarn.lock
Labels: waiting for review

#22 fix multiple router error
  src/routes/contentReviews/index.js
  src/routes/contents/index.js
  src/routes/index.js
Labels: bug

#23 content types constants added
  src/constants/content.js
  src/models/contents.js
  src/pre_handlers/authantication.js
Labels: enhancement

#25 user seeder added
  package.json
  seeders/20210708082941-demo-user.js
Labels: enhancement

#26 images tablosu seeder
  seeders/20210708160750-images.js
Labels: waiting for review

#24 Added get operations of reviews
  migrations/20210621122903-create-content-reviews.js
  src/models/contentReviews.js
  src/routes/contentReviews/index.js
Labels: waiting for review

#28 Discussions tablosu seeder
  seeders/20210708160750-images.js
  seeders/20210708213048-discussions.js
Labels: waiting for review

#27 Wanted contents update and seed
  .gitignore
  migrations/20210601155244-create-images.js
  migrations/20210601182648-create-content.js
  migrations/20210606170510-create-wanted-contents.js
  seeders/20210708082941-demo-user.js
  seeders/20210709052955-demo-wanted-content.js
  src/models/contents.js
  src/models/users.js
  src/models/wantedContents.js
  src/routes/wantedContents/index.js
Labels: enhancement, waiting for review

#31 content limit added
  src/routes/contents/index.js
Labels: waiting for review

#33 added associations
  src/models/comments.js
  src/models/contentReviews.js
  src/models/discussions.js
  src/models/users.js
Labels: waiting for review

#35 added include
  src/routes/contents/index.js
Labels: waiting for review

#38 content tablosu include işlemi
  src/routes/contents/index.js
Labels: waiting for review
