Repository mavidurak/orientation-api, pull requests merged in 2021-08, with the labels that each got.

#39 fixed syntax errors
  src/routes/contents/index.js
Labels: waiting for review

#40 E-mail doğrulaması eklendi
  migrations/20210729004806-create-email-confirmation-tokens.js
  package.json
  sample.env
  src/constants/api.js
  src/constants/email.js
  src/models/emailConfirmationTokens.js
  src/models/users.js
  src/routes/authentication/index.js
  src/templates/emailConfirm.html
  src/utils/sendEmail.js
Labels: waiting for review

#34 Message Table model Migration CRUD and seed
  migrations/20210713150122-create-messages.js
  seeders/20210713160650-demo-messages.js
  src/models/contents.js
  src/models/messages.js
  src/models/users.js
  src/routes/messages/index.js
  src/routes/wantedContents/index.js
Labels: enhancement, waiting for review

#43 Hotfix messages
  migrations/20210713150122-create-messages.js
  seeders/20210713160650-demo-messages.js
  src/models/messages.js
Labels: bug

#53 hotfix-51
  migrations/20210821122903-update-contents-and-reviews-score-type.js
  src/models/contentReviews.js
  src/models/contents.js
  src/routes/contentReviews/index.js
  src/utils/generateSlug.js
Labels: waiting for review

#57 organizers and members added
  src/routes/communities/index.js
Labels: waiting for review

#56 api change for mycontents page
  src/routes/contentReviews/index.js
Labels: enhancement, waiting for review
